### ISSUE TITLE
Setup Email Collection 

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage#49]
Prompt the user for their email address: 

Reason: 

* Interest in visiting an Installation
* Interest in hosting an Installation

**Comment by wonderwoman13** [comment]
@danigirl329 

Branch: email-collection 

I've setup Interest collection on the homepage. Please pull it down and take a look to see if we can design a homepage that compelling catches interest.

**Comment by danigirl329** [comment]
I styled the form, not sure if we want this to be static on the installations page or if we want this to be a popup.
I also changed the submission to ajax so I can do some fadeout/thank you animations and error handling
I need a bad request to come back from the create controller, because the create validates automatically against the same email addresses from being submitted. Otherwise, a js error is created which would cause any other scripts on the page to fail.
